package com.apimonitoring.backend.service;

import com.apimonitoring.backend.model.ApiService;
import com.apimonitoring.backend.model.Incident;

import jakarta.annotation.PostConstruct;
import com.apimonitoring.backend.repository.*;
import org.springframework.stereotype.Service;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@Service
public class MonitoringService {

    private final ApiServiceRepository apiServiceRepository;
    private final IncidentRepository incidenteRepository;
    private Long incidentIdCounter = 3L;

    private final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm a ");
    private final ZoneId zoneId = ZoneId.of("America/New_York");
 
    
    public MonitoringService(ApiServiceRepository apiServiceRepository, IncidentRepository incidenteRepository) {
        this.apiServiceRepository = apiServiceRepository;
        this.incidenteRepository = incidenteRepository;

    }
    @PostConstruct
    public void initData() { 
        if (apiServiceRepository.count() == 0) {
        apiServiceRepository.save(new ApiService(null, "Entitlements API", "Wealth Platform", "PROD", "Healthy", 120, 0.2, "2026-05-28 10:30 AM"));
        apiServiceRepository.save(new ApiService(null, "Payments API", "Transfer Services", "DEV", "Degraded", 450, 3.1, "2026-05-28 10:28 AM"));
        apiServiceRepository.save(new ApiService(null, "User Profile API", "Customer Data", "UAT", "Down", 900, 8.5, "2026-05-28 10:25 AM"));
        apiServiceRepository.save(new ApiService(null, "Notification API", "Messaging", "PROD", "Healthy", 180, 0.5, "2026-05-28 10:31 AM"));
        }

        if (incidenteRepository.count() == 0) {

        incidenteRepository.save(new Incident(null, "Payments API", "Elevated response times", "High", "Open",
                "Payments API is experiencing slower than normal response times.", "2026-05-28 09:45 AM"));

        incidenteRepository.save(new Incident(null, "User Profile API", "Service unavailable in UAT", "Critical", "Open",
                "User Profile API is returning errors during UAT validation.", "2026-05-28 09:15 AM"));
        }
    }

    public List<ApiService> getServices() {
        return apiServiceRepository.findAll();
    }

    public List<Incident> getIncidents() {
        return incidenteRepository.findAll();
    }

    public Incident createIncident(Incident incident) {
        incident.setId(null);  // Ensure ID is generated by the database
        incident.setStatus("Open");
        incident.setCreatedAt(ZonedDateTime.now(zoneId).format(formatter));
        incidenteRepository.save(incident);
        return incident;
    }

    public Optional<Incident> resolveIncident(Long id) {
     return incidenteRepository.findById(id).map(incident -> {
      incident.setStatus("Resolved");
      incidenteRepository.save(incident);
      return incident;
    });
}
}
